/*
                    *****  Group No. - 9  *****
        Name : Sarthak Shah                 ID : 2020A7PS0092P
        Name : BhanuPratap Singh Rathore    ID : 2020A7PS1675P
        Name : Archaj Jain                  ID : 2020A7PS0072P
        Name : Siddharth Khandelwal         ID : 2020A7PS0098P
        Name : Rishi Rakesh Shrivastava     ID : 2020A7PS0108P

*/

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>

#include "removeComments.h"
#include "lexer.h"
#include "parser.h"

#define BUFF_SIZE 5000

void printMenu()
{
    printf("\t Select the option you want to see\n ");
    printf("\n------------------------------------------------------\n");
    printf("\n 0 -> for exit\n");
    printf("\n 1 -> Print the comment removed source code\n");
    printf("\n 2 -> Print tokens generated by lexer\n");
    printf("\n 3 -> Print the Parse Tree\n");
    printf("\n 4 -> Print the Total Time taken\n");
}
void displayInfo(){
    printf("\n     ------------------------------------------------------\n");
    printf("\033[32m");
    printf("\n\t FIRST and FOLLOW set automated\n");
    printf("\t Both lexical and syntax analysis module developed\n");
    printf("\t modules work with all testcases\n");
    printf("\t Parse tree is constructed for all testcases\n");
    printf("\033[0m");
    printf("\n     ------------------------------------------------------\n\n");

}
int main(int argc, char *argv[])
{
    displayInfo();
    if (argc < 4)
    {
        printf("very few arguments\n");
        exit(0);
    }
    FILE *fp = NULL;
    fp = fopen(argv[1], "r");
    if (fp == NULL)
    {
        printf("error in opening file\n");
    }
    FILE *fp1 = NULL;
    fp1 = fopen(argv[2], "w");
    while (true)
    {
        fp = fopen(argv[1], "r");
        printMenu();
        printf("Please Enter the Choice\n");
        int x;
        scanf("%d", &x);
        printf("\n");
        switch (x)
        {
        case 0:
        {
            printf("\nTERMINATING THE PROGRAM\n");
            exit(0);
        }
        case 1:
        {
            char buffer[BUFF_SIZE], cleanFile[BUFF_SIZE];
            fread(buffer, sizeof(char), BUFF_SIZE, fp);
            char *testCaseFile = buffer;
            removeComments(testCaseFile, cleanFile);
            puts(cleanFile);
            break;
        }

        case 2:
        {
            print_tokens(fp, atoi(argv[3]));
            break;
        }

        case 3:
        {
            fp1 = fopen(argv[2], "w");
            setbuf(fp1, NULL);
            parseTreeNode root = startParser(fp, atoi(argv[3]));
            openparsetreefile(fp1);

            fprintf(fp1, "       LEXEME       ");
            fprintf(fp1, "  LINE_NO  ");
            fprintf(fp1, "     TOKEN-TYPE      ");
            fprintf(fp1, "  VALUE if NUM/RNUM  ");
            fprintf(fp1, "       PARENT       ");
            fprintf(fp1, "   IS A LEAF NODE  ");
            fprintf(fp1, "    NON-TERMINAL     ");
            fprintf(fp1, "\n\n");

            printParseTree(root);
            break;
        }

        case 4:
        {
            clock_t start_time, end_time;
            double total_CPU_time, total_CPU_time_in_seconds;
            start_time = clock();

            // PARSER CODE HERE
            startParser(fp, atoi(argv[3]));

            end_time = clock();

            total_CPU_time = (double)(end_time - start_time);

            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

            printf("TOTAL CPU CLOCK TICKS := %lf \n", total_CPU_time);
            printf("TOTAL CPU TIME IN SECONDS := %lf \n", total_CPU_time_in_seconds);
            break;
        }
        }
        printf("\n\n");
    }
}